# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  azure-cli,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0m6qljf9m3dm2qy3f1k8ivh7nb48r5nwgyxa8wxhrwmhflql950r";
    aarch64-linux = "15pr1i7pls72smlz8phvmqcs16wgzv1zm37v73b6acpqr8mvbbg2";
    x86_64-darwin = "0piyl29cb5jx5y2paxd7h943ki5n0hxcwgq9mbsw4956dcqml1rq";
    aarch64-darwin = "0slqs9s9whacwmg5pkhbad42hkd6z2bcl03jmdb3li92glk6clfl";
  };

  urlMap = {
    x86_64-linux = "https://github.com/lvlcn-t/azctx/releases/download/v0.4.3/azctx_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/lvlcn-t/azctx/releases/download/v0.4.3/azctx_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/lvlcn-t/azctx/releases/download/v0.4.3/azctx_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/lvlcn-t/azctx/releases/download/v0.4.3/azctx_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "azctx";
  version = "0.4.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./azctx $out/bin/azctx
    wrapProgram $out/bin/azctx --prefix PATH : ${lib.makeBinPath ([ azure-cli ])}
    installShellCompletion --cmd azctx \
    --bash completions/azctx.bash \
    --fish completions/azctx.fish \
    --zsh completions/azctx.zsh
  '';

  meta = {
    description = "Faster way to switch between Azure tenants and subscriptions with az";
    homepage = "https://github.com/lvlcn-t/azctx";
    license = lib.licenses.mit;
    mainProgram = "azctx";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
